{
  "checkpoints": [
    "{\n  \"trainable_name\": \"PPO\",\n  \"trial_id\": \"b74b1_00000\",\n  \"config\": {\n    \"env\": \"TradingEnv\",\n    \"model\": {\n      \"fcnet_hiddens\": [\n        256,\n        256\n      ],\n      \"fcnet_activation\": \"relu\",\n      \"use_lstm\": true,\n      \"max_seq_len\": 40,\n      \"lstm_cell_size\": 256,\n      \"lstm_use_prev_action\": true,\n      \"lstm_use_prev_reward\": true\n    },\n    \"env_config\": {\n      \"window_size\": 25\n    },\n    \"log_level\": \"DEBUG\",\n    \"framework\": \"torch\",\n    \"ignore_worker_failures\": true,\n    \"num_workers\": 1,\n    \"num_gpus\": 0,\n    \"clip_rewards\": true,\n    \"lr\": 8e-06,\n    \"gamma\": 0,\n    \"observation_filter\": \"MeanStdFilter\",\n    \"lambda\": 0.72,\n    \"vf_loss_coeff\": 0.5,\n    \"entropy_coeff\": 0.01,\n    \"eager_tracing\": true\n  },\n  \"local_dir\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO\",\n  \"evaluated_params\": {},\n  \"experiment_tag\": \"0\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 1,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 1,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"stopping_criterion\": {\n    \"training_iteration\": 30\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1612844675.8699155,\n  \"logdir\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/PPO_TradingEnv_b74b1_00000_0_2021-02-09_12-24-35\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/PPO_TradingEnv_b74b1_00000_0_2021-02-09_12-24-35/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 519, in _process_trial\\n    result = self.trial_executor.fetch_result(trial)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 497, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/worker.py\\\", line 1379, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(KeyError): \\u001b[36mray::PPO.train()\\u001b[39m (pid=2727669, ip=192.168.88.226)\\n  File \\\"python/ray/_raylet.pyx\\\", line 422, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 456, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 459, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 463, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 415, in ray._raylet.execute_task.function_executor\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\\\", line 106, in __init__\\n    Trainer.__init__(self, config, env, logger_creator)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\\\", line 465, in __init__\\n    super().__init__(config, logger_creator)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 96, in __init__\\n    self.setup(copy.deepcopy(self.config))\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\\\", line 629, in setup\\n    self._init(self.config, self.env_creator)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\\\", line 133, in _init\\n    self.workers = self._make_workers(\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\\\", line 700, in _make_workers\\n    return WorkerSet(\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py\\\", line 79, in __init__\\n    remote_spaces = ray.get(self.remote_workers(\\nray.exceptions.RayTaskError(KeyError): \\u001b[36mray::RolloutWorker.foreach_policy()\\u001b[39m (pid=2727675, ip=192.168.88.226)\\n  File \\\"/home/davidfan/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py\\\", line 2895, in get_loc\\n    return self._engine.get_loc(casted_key)\\n  File \\\"pandas/_libs/index.pyx\\\", line 70, in pandas._libs.index.IndexEngine.get_loc\\n  File \\\"pandas/_libs/index.pyx\\\", line 101, in pandas._libs.index.IndexEngine.get_loc\\n  File \\\"pandas/_libs/hashtable_class_helper.pxi\\\", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item\\n  File \\\"pandas/_libs/hashtable_class_helper.pxi\\\", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item\\nKeyError: 'Date'\\n\\nThe above exception was the direct cause of the following exception:\\n\\n\\u001b[36mray::RolloutWorker.foreach_policy()\\u001b[39m (pid=2727675, ip=192.168.88.226)\\n  File \\\"python/ray/_raylet.pyx\\\", line 422, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 456, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 459, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 463, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 415, in ray._raylet.execute_task.function_executor\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\\\", line 372, in __init__\\n    self.env = _validate_env(env_creator(env_context))\\n  File \\\"main_simple.py\\\", line 163, in create_env\\n    Stream.source(list(data[\\\"Date\\\"][k:w])).rename(\\\"date\\\"),\\n  File \\\"/home/davidfan/.local/lib/python3.8/site-packages/pandas/core/frame.py\\\", line 2902, in __getitem__\\n    indexer = self.columns.get_loc(key)\\n  File \\\"/home/davidfan/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py\\\", line 2897, in get_loc\\n    raise KeyError(key) from err\\nKeyError: 'Date'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": true,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_nonjson_fields\": [\n    \"results\",\n    \"best_result\",\n    \"param_config\",\n    \"extra_arg\"\n  ],\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_metric": null,
    "_total_time": 0,
    "_iteration": 2,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1612844675.849427,
    "_last_checkpoint_time": 1612844679.652355,
    "_checkpoint_period": 10,
    "_session_str": "2021-02-09_12-24-35",
    "checkpoint_file": "/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/experiment_state-2021-02-09_12-24-35.json",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1612844675.849427,
    "timestamp": 1612844679.652355
  }
}